### ISSUE TITLE
app.getAllContext() returns empty object

### ISSUE THREAD

**Issue by piurafunk** [aws/constructs#2239]
I am attempting to parse some context values from the CDK app. The feature was introduced by https://github.com/aws/constructs/pull/1751

My code snippet is:

```
const app = new cdk.App();
console.log(app.node.getAllContext());
```

Which outputs:
```
{}
```

However, when I toss a `console.log()` in `Node.getAllContext()`, it prints my context variables:

```
console.log(this._context)
```

Outputs:
```
...
  '@aws-cdk/aws-ec2:restrictDefaultSecurityGroup': true,
  '@aws-cdk/aws-apigateway:requestValidatorUniqueId': true,
  longTermStorageBucketArn: 'backups-690e',
  'aws:cdk:enable-path-metadata': true,
  'aws:cdk:enable-asset-metadata': true,
...
```

Where `longTermStorageBucketArn` is the context I have passed on command line:

```
npm run cdk -- -c longTermStorageBucketArn=backups-690e synth
```

---

I also tested it in the constructor of a `Stack` object:

```
console.log('all context', this.node.getAllContext())
// as well as
console.log('all context', scope.node.getAllContext())
```

both of which produce:

```
all context {}
```

---

Is this the intended behavior? I don't seem to understand how to get all context from the `app` object, whereas `app.node.getContext(...)` works as expected.

**Comment by matt9ucci** [comment]
I noticed that the `getAllContext` method returns the value of `defaults` arg or `{}` instead of contexts when the construct is a root node (the scope is `undefined`).
https://github.com/aws/constructs/blob/d5eb5ff48d22ce3cd3f38b762c1be890aec5dd9d/src/construct.ts#L248-L252

The `cdk.App()` is a root node. Therefore, its `getAllContext` method never returns its contexts.
